// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    Request,
    Result,
    ValidateRequest,
    ValidateResult,
    XPathRequest,
    XPathResult
} from "./models.js";
