// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../internal/engine/models.js";

export type Request = engine$0.Request;

export type Result = engine$0.Result;

/**
 * XSD schema-validation API.
 */
export type ValidateRequest = engine$0.ValidateRequest;

export type ValidateResult = engine$0.ValidateResult;

/**
 * Standalone XPath 3.1 evaluation API.
 */
export type XPathRequest = engine$0.XPathRequest;

export type XPathResult = engine$0.XPathResult;
