// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LicenseService exposes this project's own license and every bundled
 * third-party dependency's license text to the frontend, for a visible
 * "Licenses" view. See desktop/licenses/licenses.go for what's included and
 * how to update it after a dependency change.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * List returns every bundled license, project first.
 */
export function List(): $CancellablePromise<$models.License[] | null> {
    return $Call.ByID(4099124706);
}
