// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * License is the frontend-facing shape of licenses.Entry, with the text
 * already resolved into a plain field (a method value wouldn't survive the
 * bindings' JSON serialization).
 */
export interface License {
    "Name": string;
    "Version": string;
    "License": string;
    "Kind": string;
    "URL": string;
    "Text": string;
}
