// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService is the Wails service backing the Postman-like project
 * workbench: a project registry, a per-project file tree, file CRUD, and the
 * saved-run manifest. Actually running a saved run still goes through
 * XsltService.RunTransform/RunValidate/RunXPath — this service only manages
 * the project's files and metadata.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "./internal/project/models.js";

/**
 * CreateFile creates a new file at rel seeded with content. It fails if
 * something already exists there.
 */
export function CreateFile(dir: string, rel: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2260004922, dir, rel, content);
}

/**
 * CreateFolder creates a new folder at rel (and any missing parents).
 */
export function CreateFolder(dir: string, rel: string): $CancellablePromise<void> {
    return $Call.ByID(2269160984, dir, rel);
}

/**
 * CreateProject creates a new, seeded project inside the managed library
 * folder and opens it.
 */
export function CreateProject(name: string): $CancellablePromise<project$0.Project | null> {
    return $Call.ByID(3794430337, name);
}

/**
 * Delete permanently removes the file or folder at rel. There is no undo —
 * the frontend must confirm with the user first.
 */
export function Delete(dir: string, rel: string): $CancellablePromise<void> {
    return $Call.ByID(3223581587, dir, rel);
}

/**
 * Duplicate copies the file at rel to an automatically-numbered sibling path
 * and returns the new project-relative path.
 */
export function Duplicate(dir: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(230797401, dir, rel);
}

/**
 * ForgetProject removes dir from the project registry without touching
 * anything on disk.
 */
export function ForgetProject(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2005269066, dir);
}

/**
 * ListProjects returns known projects (newest-opened first) for the sidebar
 * project switcher.
 */
export function ListProjects(): $CancellablePromise<project$0.Ref[] | null> {
    return $Call.ByID(1083075410);
}

/**
 * OpenProject loads (creating if necessary) the project at dir: its
 * manifest — migrating a legacy goxslt.workspace.json if that's all that's
 * present — plus a fresh file tree scan. It also registers dir in the
 * project registry.
 */
export function OpenProject(dir: string): $CancellablePromise<project$0.Project | null> {
    return $Call.ByID(3378515093, dir);
}

/**
 * PickFolder opens a native folder picker and returns the chosen path (empty
 * if the user cancels) — used both for "Open folder as project" and any
 * other folder-selection need.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(2105207105);
}

/**
 * ReadFile returns the content of the file at rel within the project rooted
 * at dir.
 */
export function ReadFile(dir: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(1365949130, dir, rel);
}

/**
 * RefreshTree rescans dir's file tree, picking up changes made outside the
 * app (git checkout, another editor, …).
 */
export function RefreshTree(dir: string): $CancellablePromise<project$0.Node | null> {
    return $Call.ByID(2299638319, dir);
}

/**
 * Rename moves the file or folder at fromRel to toRel within the project
 * rooted at dir (also used for drag-and-drop moves between folders).
 */
export function Rename(dir: string, fromRel: string, toRel: string): $CancellablePromise<void> {
    return $Call.ByID(4872810, dir, fromRel, toRel);
}

/**
 * Reveal shows the file or folder at rel in the platform file manager
 * (Finder on macOS, Explorer on Windows), reusing the same containment-
 * checked path resolution as every other file operation so this can't be
 * used to reveal something outside the project.
 */
export function Reveal(dir: string, rel: string): $CancellablePromise<void> {
    return $Call.ByID(2085297517, dir, rel);
}

/**
 * SaveManifest persists the project's manifest (name, saved runs, UI state).
 */
export function SaveManifest(dir: string, m: project$0.Manifest): $CancellablePromise<void> {
    return $Call.ByID(2583612900, dir, m);
}

/**
 * WriteFile overwrites the file at rel with content — the autosave
 * primitive; the frontend debounces calls per path and flushes pending
 * writes before every run.
 */
export function WriteFile(dir: string, rel: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1511688169, dir, rel, content);
}
