// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * XsltService is the Wails service exposed to the frontend for running the
 * engine. Its exported methods are bound to TypeScript by the Wails binding
 * generator. Project/file management lives in ProjectService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "../engine/models.js";

/**
 * RunTransform compiles and executes an XSLT transformation and returns the
 * serialized output together with any diagnostics.
 */
export function RunTransform(req: engine$0.Request): $CancellablePromise<engine$0.Result> {
    return $Call.ByID(3851859095, req);
}

/**
 * RunValidate validates an XML instance against one or more XSD schemas
 * (version "1.0" or "1.1") and returns the validity plus any diagnostics.
 */
export function RunValidate(req: engine$0.ValidateRequest): $CancellablePromise<engine$0.ValidateResult> {
    return $Call.ByID(1338143807, req);
}

/**
 * RunXPath evaluates a standalone XPath 3.1 expression, optionally against a
 * context XML document (req.Source may be empty for expressions needing no
 * input, e.g. "1 + 2" or "current-dateTime()").
 */
export function RunXPath(req: engine$0.XPathRequest): $CancellablePromise<engine$0.XPathResult> {
    return $Call.ByID(3140449084, req);
}
