// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../time/models.js";

/**
 * FileKind classifies a file by extension, purely to drive icons and
 * default pickers in the UI — it has no effect on what the engine accepts.
 */
export enum FileKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * .xsl, .xslt
     */
    KindStylesheet = "stylesheet",

    /**
     * .xsd
     */
    KindSchema = "schema",

    /**
     * .xml
     */
    KindXML = "xml",

    /**
     * .json, .txt, .csv, .html, .md
     */
    KindText = "text",
    KindOther = "other",
};

/**
 * Manifest is the on-disk project description.
 */
export interface Manifest {
    "schema": number;
    "name": string;
    "runs": Run[] | null;
    "ui": UIState;
}

/**
 * Node is one entry in a scanned project file tree. Path is project-relative
 * and always slash-separated, regardless of host OS.
 */
export interface Node {
    "name": string;
    "path": string;
    "dir": boolean;
    "kind"?: FileKind;
    "children"?: (Node | null)[] | null;
}

/**
 * Project is a loaded manifest plus its absolute folder path and scanned file
 * tree.
 */
export interface Project {
    "dir": string;
    "manifest": Manifest;
    "tree": Node | null;
}

/**
 * Ref is one entry in the project registry: enough to list and reopen a
 * project without scanning its tree.
 */
export interface Ref {
    "dir": string;
    "name": string;
    "lastOpened": time$0.Time;
}

/**
 * Run is one saved, reusable run configuration — the Postman "request"
 * analogue. Which fields are meaningful depends on Kind. Paths are always
 * project-relative, slash-separated.
 */
export interface Run {
    "id": string;
    "name": string;
    "kind": RunKind;

    /**
     * sidebar grouping, "" = ungrouped
     */
    "folder"?: string;

    /**
     * transform
     */
    "stylesheet"?: string;
    "source"?: string;
    "params"?: { [_ in string]?: string } | null;
    "initialTemplate"?: string;

    /**
     * validate. Schemas is an ordered multi-file schema set for xs:import/
     * xs:include/xs:redefine across real project files; when it's empty, the
     * UI instead offers a single inline schema (SchemaInline) typed directly
     * into the run itself, no project file required — the quick-validate
     * path. Instance works the same way against InstanceInline.
     */
    "schemas"?: string[] | null;
    "schemaInline"?: string;
    "instance"?: string;
    "instanceInline"?: string;

    /**
     * "1.0" | "1.1"
     */
    "xsdVersion"?: string;

    /**
     * xpath. ContextDoc is a project file reference; when empty, the UI
     * offers inline context text (ContextInline) instead — same quick-start
     * shape as validate's InstanceInline.
     */
    "expression"?: string;

    /**
     * "" = no context document
     */
    "contextDoc"?: string;
    "contextInline"?: string;
}

/**
 * RunKind identifies which engine entry point a saved run drives.
 */
export enum RunKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RunTransform = "transform",
    RunValidate = "validate",
    RunXPath = "xpath",
};

/**
 * UIState is small persisted UI state that isn't worth losing across
 * restarts but also isn't meaningful engine input.
 */
export interface UIState {
    /**
     * expanded folder paths in the file tree
     */
    "expanded"?: string[] | null;
}
