// Thin wrapper over the generated Wails bindings (frontend/bindings/…,
// regenerated by `make bindings`). The generated interfaces are real
// TypeScript (see desktop/Makefile's `-ts` flag) — re-export them directly
// here rather than hand-mirroring the Go structs, so a struct change only
// ever needs a `make bindings` + a look at what broke.
//
// A couple of names are aliased on the way out:
//   - project.Node -> FileNode, to avoid shadowing the DOM's global `Node`.
//   - project.Run  -> SavedRun, project.Manifest -> ProjectManifest,
//     project.Ref  -> ProjectRef: the bare Go names are too generic once
//     they sit next to everything else in this module.
import { XsltService, ProjectService, LicenseService } from "../../bindings/github.com/tim-riep/go-xslt/desktop";
import { type License } from "../../bindings/github.com/tim-riep/go-xslt/desktop/models";
// The "engine" package barrel only re-exports the request/response types that
// are themselves a bound method's parameter/return type (Request, Result, …);
// field-only types (Diagnostic, SecondaryOutput, XPathItem) and XSDVersion
// live solely at their point of definition, internal/engine — import
// everything from there instead of splitting across both barrels.
import {
  XSDVersion,
  type Diagnostic,
  type Request as TransformRequest,
  type Result as TransformResult,
  type SecondaryOutput,
  type ValidateRequest,
  type ValidateResult,
  type XPathRequest,
  type XPathResult,
  type XPathItem,
} from "../../bindings/github.com/tim-riep/go-xslt/internal/engine";
import {
  FileKind,
  RunKind,
  type Project,
  type Manifest as ProjectManifest,
  type Run as SavedRun,
  type Node as FileNode,
  type Ref as ProjectRef,
} from "../../bindings/github.com/tim-riep/go-xslt/desktop/internal/project";

export type {
  Diagnostic,
  TransformRequest,
  TransformResult,
  SecondaryOutput,
  ValidateRequest,
  ValidateResult,
  XPathRequest,
  XPathResult,
  XPathItem,
  Project,
  ProjectManifest,
  SavedRun,
  FileNode,
  ProjectRef,
  License,
};
export { XSDVersion, FileKind, RunKind };

// ---- engine ----

export function runTransform(req: TransformRequest) {
  return XsltService.RunTransform(req);
}

export function runValidate(req: ValidateRequest) {
  return XsltService.RunValidate(req);
}

export function runXPath(req: XPathRequest) {
  return XsltService.RunXPath(req);
}

// ---- projects ----

export function listProjects() {
  return ProjectService.ListProjects();
}

export function createProject(name: string) {
  return ProjectService.CreateProject(name);
}

export function pickFolder() {
  return ProjectService.PickFolder();
}

export function openProject(dir: string) {
  return ProjectService.OpenProject(dir);
}

export function forgetProject(dir: string) {
  return ProjectService.ForgetProject(dir);
}

export function refreshTree(dir: string) {
  return ProjectService.RefreshTree(dir);
}

export function saveManifest(dir: string, manifest: ProjectManifest) {
  return ProjectService.SaveManifest(dir, manifest);
}

export function reveal(dir: string, rel: string) {
  return ProjectService.Reveal(dir, rel);
}

// ---- project files ----

export function readFile(dir: string, rel: string) {
  return ProjectService.ReadFile(dir, rel);
}

export function writeFile(dir: string, rel: string, content: string) {
  return ProjectService.WriteFile(dir, rel, content);
}

export function createFile(dir: string, rel: string, content = "") {
  return ProjectService.CreateFile(dir, rel, content);
}

export function createFolder(dir: string, rel: string) {
  return ProjectService.CreateFolder(dir, rel);
}

export function renamePath(dir: string, fromRel: string, toRel: string) {
  return ProjectService.Rename(dir, fromRel, toRel);
}

export function deletePath(dir: string, rel: string) {
  return ProjectService.Delete(dir, rel);
}

export function duplicatePath(dir: string, rel: string) {
  return ProjectService.Duplicate(dir, rel);
}

// ---- licenses ----

export function listLicenses() {
  return LicenseService.List();
}
