// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    XSDVersion
} from "./models.js";

export type {
    Diagnostic,
    Request,
    Result,
    SecondaryOutput,
    ValidateRequest,
    ValidateResult,
    XPathItem,
    XPathRequest,
    XPathResult
} from "./models.js";
