// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Diagnostic is a single error or warning produced while compiling or running
 * a transformation. Line/Col are 1-based; 0 means "unknown".
 */
export interface Diagnostic {
    "severity": string;
    "line": number;
    "col": number;

    /**
     * Code is a W3C-style error code where known (e.g. "XPST0003").
     */
    "code": string;
    "message": string;

    /**
     * Phase is where the diagnostic originated: "parse", "compile" or "run".
     */
    "phase": string;
}

/**
 * Request is a single transformation request.
 */
export interface Request {
    /**
     * Stylesheet is the XSLT source text.
     */
    "stylesheet": string;

    /**
     * Source is the XML input document. May be empty when InitialTemplate is set.
     */
    "source": string;

    /**
     * Params are top-level stylesheet parameters (string-typed for now).
     */
    "params": { [_ in string]?: string } | null;

    /**
     * InitialTemplate optionally names an xsl:template to invoke first
     * (xsl:initial-template) instead of matching against the source root.
     */
    "initialTemplate": string;

    /**
     * BaseDir is the workspace directory used to resolve relative URIs in
     * xsl:import/xsl:include, document()/doc(), unparsed-text(), and to write
     * xsl:result-document. Empty disables disk resolution.
     */
    "baseDir": string;
}

/**
 * Result is the outcome of a transformation. Output holds the serialized
 * result tree; Diagnostics holds any errors/warnings. When a fatal error
 * occurs, Output is empty and Diagnostics contains at least one error.
 */
export interface Result {
    "output": string;
    "diagnostics": Diagnostic[] | null;

    /**
     * DurationMs is wall-clock transform time in milliseconds.
     */
    "durationMs": number;

    /**
     * Method is the effective output method ("xml", "html", "text", "json").
     */
    "method": string;

    /**
     * Messages holds text emitted by xsl:message.
     */
    "messages": string[] | null;

    /**
     * SecondaryOutputs holds documents produced by xsl:result-document.
     */
    "secondaryOutputs": SecondaryOutput[] | null;
}

/**
 * SecondaryOutput is a result produced by xsl:result-document.
 */
export interface SecondaryOutput {
    "href": string;
    "content": string;
    "method": string;
}

/**
 * ValidateRequest validates an XML instance document against one or more XSD
 * schema documents.
 */
export interface ValidateRequest {
    /**
     * Schemas holds the schema document source texts. The first is the entry
     * schema; the rest are additional documents available to xs:import/include.
     */
    "schemas": string[] | null;

    /**
     * Instance is the XML instance document to validate.
     */
    "instance": string;

    /**
     * Version is "1.0" (default) or "1.1".
     */
    "version": XSDVersion;

    /**
     * BaseDir resolves relative schema locations (xs:import/xs:include/
     * xsi:schemaLocation). Empty disables disk resolution.
     */
    "baseDir": string;
}

/**
 * ValidateResult is the outcome of a validation. Valid is true iff the instance
 * is schema-valid; Diagnostics carries schema-compile and validation errors (and
 * is non-empty when Valid is false).
 */
export interface ValidateResult {
    "valid": boolean;
    "diagnostics": Diagnostic[] | null;
    "durationMs": number;
}

/**
 * XPathItem is one item of the result sequence.
 */
export interface XPathItem {
    /**
     * Type is a short label: a node kind ("element", "attribute", …), an atomic
     * type QName ("xs:integer", …), or "map"/"array"/"function".
     */
    "type": string;

    /**
     * Value is the item's string value (element/attribute string value; atomic
     * lexical form).
     */
    "value": string;
}

/**
 * XPathRequest evaluates a standalone XPath 3.1 expression, optionally against
 * an XML context document.
 */
export interface XPathRequest {
    /**
     * Expression is the XPath 3.1 expression to evaluate.
     */
    "expression": string;

    /**
     * Source is an optional XML document. When non-empty its document node is
     * the context item, so path expressions like /root/child work; when empty
     * the expression is evaluated with no context item (e.g. 1 + 2,
     * current-dateTime(), string-length('abc')).
     */
    "source": string;

    /**
     * BaseDir resolves relative URIs in fn:doc/fn:unparsed-text/fn:collection.
     * Empty disables disk resolution (those functions report the resource as
     * unavailable rather than erroring).
     */
    "baseDir": string;
}

/**
 * XPathResult is the outcome of an XPath evaluation.
 */
export interface XPathResult {
    /**
     * Value is the string value of the whole result sequence.
     */
    "value": string;

    /**
     * Items is one entry per item in the result sequence.
     */
    "items": XPathItem[] | null;

    /**
     * Count is the number of items in the result sequence.
     */
    "count": number;

    /**
     * Diagnostics carries parse/eval errors (non-empty on failure).
     */
    "diagnostics": Diagnostic[] | null;

    /**
     * DurationMs is wall-clock evaluation time in milliseconds.
     */
    "durationMs": number;
}

/**
 * XSDVersion selects the XML Schema language version for Validate.
 */
export enum XSDVersion {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * XSD10 is W3C XML Schema 1.0 (the default when Version is empty).
     */
    XSD10 = "1.0",

    /**
     * XSD11 is W3C XML Schema 1.1.
     */
    XSD11 = "1.1",
};
